### ISSUE TITLE
Incorrect summing logic in Monetization API

### ISSUE THREAD

**Issue by benhylau** [hyphacoop/api.distributed.press#9]
The summing logic here looks wrong, leading to incorrect data fed into COMPOST's bake sale:

https://ipfs.distributed.press/ipns/api.compost.digital/v0/monetization/balances.json

<img width="771" alt="Screen Shot 2021-03-22 at 8 58 32 AM" src="https://user-images.githubusercontent.com/2261308/111957853-d4151b00-8aec-11eb-9e66-395cdabf0dee.png">

See: https://one.compost.digital/support-us/

**Comment by YurkoWasHere** [comment]
Applied Code: https://github.com/hyphacoop/api.distributed.press/compare/balance-total?expand=1
Converted code for decimal shift from String Manipulation to Mathematical

**Bug:**
String manipulation method breaks when the length of the string is less then the number of decimal places.

**Example of bug:**
Balance 570  with Decimal of 6

The code to extract the decimal values from the string
```
${balStr.slice(balStr.length - decInt, balStr.length)}
```
This would be stored in memory as
`570`
`balStr.length - decInt` Should indicate the number of characters counted from the right the decimal value starts.
In this case (3 - 6 = -3) it would start before the first character, and therefore truncated.

So code would return `570` instead of `000570` making the balance `0.570`

**Solution:**
Divide the Balance by a number that is represented by 1 followed by the number of zeros in `intDec`
ie: 6 decimal places = 1000000 (or '1' = '0'repeat(6))
so 570  / 1000000

**Comment by YurkoWasHere** [comment]
@benhylau do you have any idea what the number should be?

**Comment by benhylau** [comment]
This makes sense as I never considered the case where the string would be shorter than the decimal places indicated.

We cannot however do the `x / 1000000` computation in the general case, because `x` is generally a value so large that it overflows the buffer. We must truncate _before_ doing math, hence the complex logic we have there.

I think a fix could be to keep all existing logic but add a case where we'd check if length(balanceString) < decimal places, and zero-pad any short string to 1 more digit than the decimal places. In this case, I'd expect `570 -> 0000570` so after the string manipulation it becomes `0.000570`.

**Comment by YurkoWasHere** [comment]
In that case perhaps simplying would help
used as function to run tests, code can be drop-in without functions

```
function getDecimal(balStr, decInt) { 
	balDecimal = balStr.slice(-1 * decInt); // Get last decInt characters in string
	const balWhole = balStr.slice(0,balStr.length - balDecimal.length);  // Get whole numbers in string
	balDecimal = `0`.repeat(decInt) + balDecimal; // Pad with 0s to allow shorter strings
	balDecimal = balDecimal.slice(decInt); //Get last decInt characters in string again, this time with leading 0s
	return parseFloat(balWhole + '.' + balDecimal);
}
```

Test Run:

Normal String
```
console.log(getDecimal("1234567890","5"));
```
displays `12345.6789`

```
console.log(getDecimal("1234","5"));
```
displays `0.1234`

```
console.log(getDecimal("1234567890","2"));
```
displays `12345678.9`

```
console.log(getDecimal("1234567890123456789012345678901234567890","30"));
```
displays `1234567890.1234567`

**Comment by benhylau** [comment]
>balDecimal = `0`.repeat(decInt) + balDecimal;

isn't this string-adding a bunch of zeros on top of the decimal string value?

I wonder why we cannot just check for the errored case and "fix" the string by adding this line:

```
if (balStr.length < decInt + 1) balStr = '0'.repeat(decInt + 1 - balStr.length) + balStr;
```

Try running:
```
let balStr = '570'
let decInt = 6

if (balStr.length < decInt + 1) balStr = '0'.repeat(decInt + 1 - balStr.length) + balStr;
let balFlt = parseFloat(`${balStr.slice(0, balStr.length - decInt)}.${balStr.slice(balStr.length - decInt, balStr.length)}`);

console.log(balStr)
console.log(balFlt)
```

Output:
```
0000570
0.00057
```
